#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.."

source script/env
ensure-container

# Create initramfs skeleton
rm -rf initramfs && mkdir -p initramfs
pushd initramfs
mkdir -p bin sbin etc dev proc sys usr/bin usr/sbin
mkdir dev/{pts,net,shm,input,misc}
ln -s /proc/mounts etc/mtab
rsync -rlpDSv ../skel/ .
popd # initramfs


# Build busybox
pushd busybox
cp -a ../config/busybox.config .config
make -j$(nproc)
make CONFIG_PREFIX=../initramfs install
popd # busybox


# Configure kernel
pushd linux
make LLVM=1 defconfig
make LLVM=1 kvm_guest.config
make LLVM=1 rustavailable
popd # linux

