#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Create initramfs skeleton
rm -rf initramfs && mkdir -p initramfs
pushd initramfs

mkdir -p bin sbin etc dev proc sys usr/bin usr/sbin
mkdir dev/{pts,net,shm,input,misc}

pushd dev
sudo mknod tty		c	5	0
sudo mknod tty1		c	4	1
sudo mknod tty2		c	4	2
sudo mknod tty3		c	4	3
sudo mknod tty4		c	4	4
sudo mknod ttyS0	c	4	6
sudo mknod console	c	5	1
sudo mknod null		c	1	3
sudo mknod zero		c	1	5
sudo mknod random	c	1	8
sudo mknod urandom	c	1	9
sudo mknod mem		c	1	1
sudo mknod kmem		c	1	2
sudo mknod kmsg		c	1	11
sudo mknod ram		b	1	1
sudo mknod ram0		b	1	0
sudo mknod ram1		b	1	1
sudo mknod ram2		b	1	2
sudo mknod ram3		b	1	3
sudo mknod loop		b	7	0
sudo mknod ptmx		c	5	2

ln -s /proc/self/fd/0 stdin
ln -s /proc/self/fd/1 stdout
ln -s /proc/self/fd/2 stderr
popd # dev

ln -s /proc/mounts etc/mtab
rsync -rlpDSv ../skel/ .
popd # initramfs


# Build busybox
pushd busybox
cp -a ../config/busybox.config .config
make -j$(nproc)
make CONFIG_PREFIX=../initramfs install
popd # busybox


# Configure kernel
pushd linux
make defconfig
make kvm_guest.config
popd # linux

